apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "app.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "app.labels" . | nindent 8 }}
    spec:
      initContainers:
      - name: migrate-database
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["php", "artisan", "migrate", "--force"]
        env:
          {{ range .Values.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{ end }}
        resources:
          {{ toYaml .Values.resources | nindent 12 }}
      containers:
        - name: laravel
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{ range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{ end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}