app_name = "laravel-k8s-tf-eks"
github_organization = "jonerickson"
github_repository = "laravel-k8s-tf-eks"
host = "laraveleks.deschutesdesigngroup.com"
region = "us-west-2"
repository_name = "laravel-k8s-tf"