apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" . }}
  labels:
    {{ include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{ include "redis.labels" . | nindent 4 }}