{{- if .Values.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.name" . }}-secret
  labels:
    {{ include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  rootPassword: {{ .Values.mysql.rootPassword | b64enc | quote }}
  database: {{ .Values.mysql.database | b64enc | quote }}
  user: {{ .Values.mysql.user | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
{{- end -}}