apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}
  labels:
    {{ include "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
      protocol: TCP
  selector:
    {{ include "mysql.labels" . | nindent 4 }}