{{- if .Values.minio.useSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.name" . }}-secret
  labels:
    {{ include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  rootUser: {{ .Values.minio.rootUser | b64enc | quote }}
  rootPassword: {{ .Values.minio.rootPassword | b64enc | quote }}
{{- end -}}