apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.name" . }}
  labels:
    {{ include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.consolePort }}
      targetPort: {{ .Values.service.consolePort }}
      protocol: TCP
      name: console
  selector:
    {{ include "minio.labels" . | nindent 4 }}