apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: laravel-k8s-tf-eks
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard