apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: laravel-k8s-tf-eks
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard