apiVersion: v1
kind: Service
metadata:
  namespace: laravel-k8s-tf-eks
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP