apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: laravel-k8s-tf-eks
  name: minio
  labels:
    app: minio
    tier: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":8900"
          env:
            - name: MINIO_ROOT_USER
              value: "laravel"
            - name: MINIO_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 8900
              name: console
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          livenessProbe:
            exec:
              command:
                - mc
                - ready
                - local
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio