apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: laravel-k8s-tf-eks
  name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard