apiVersion: v1
kind: Service
metadata:
  namespace: laravel-k8s-tf-eks
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 8900
      targetPort: 8900
  type: ClusterIP