replicaCount: 1

image:
  repository: minio/minio
  tag: "RELEASE.2023-03-20T20-16-18Z"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  apiPort: 9000
  consolePort: 8900

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

minio:
  rootUser: "laravel"
  rootPassword: "password"
  useSecret: false

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"