name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: us-west-2

jobs:
  terraform:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan -detailed-exitcode
          echo "PLAN_EXIT_CODE=$?" >> $GITHUB_ENV
        env:
          TF_VAR_region: ${{ env.AWS_REGION }}

      - name: Terraform Apply
        if: env.PLAN_EXIT_CODE == '2'
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_region: ${{ env.AWS_REGION }}

      - name: Get ECR Repository Information
        id: ecr
        working-directory: ./terraform
        run: |
          echo "ECR_REPOSITORY=$(terraform output -raw repository_name)" >> $GITHUB_ENV
          echo "ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:latest .

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ env.ECR_REPOSITORY_URL }}:latest

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ env.ECR_REPOSITORY_URL }}}:latest